define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/Validation.js":
/*!**************************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/Validation.js ***!
  \**************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "Validation": () => (/* binding */ Validation)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function Validation() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var p0 = document.querySelector('.mx-name-id_0');
  var p1 = document.querySelector('.mx-name-id_1');
  var p2 = document.querySelector('.mx-name-id_2');
  var p3 = document.querySelector('.mx-name-id_3');
  var p4 = document.querySelector('.mx-name-id_4');
  var p5 = document.querySelector('.mx-name-id_5');
  var p6 = document.querySelector('.mx-name-id_6');
  var p7 = document.querySelector('.mx-name-id_7');
  var p8 = document.querySelector('.mx-name-id_8');

  if (p0.textContent === "X" && p1.textContent === "X" && p2.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p3.textContent === "X" && p4.textContent === "X" && p5.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p6.textContent === "X" && p7.textContent === "X" && p8.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p0.textContent === "X" && p3.textContent === "X" && p6.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p1.textContent === "X" && p4.textContent === "X" && p7.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p2.textContent === "X" && p5.textContent === "X" && p8.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p0.textContent === "X" && p4.textContent === "X" && p8.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p2.textContent === "X" && p4.textContent === "X" && p6.textContent === "X") {
    message.textContent = "PLAYER X WIN!";
  } else if (p0.textContent === "O" && p1.textContent === "O" && p2.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p3.textContent === "O" && p4.textContent === "O" && p5.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p6.textContent === "O" && p7.textContent === "O" && p8.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p0.textContent === "O" && p3.textContent === "O" && p6.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p1.textContent === "O" && p4.textContent === "O" && p7.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p2.textContent === "O" && p5.textContent === "O" && p8.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p0.textContent === "O" && p4.textContent === "O" && p8.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p2.textContent === "O" && p4.textContent === "O" && p6.textContent === "O") {
    message.textContent = "PLAYER O WIN!";
  } else if (p0.textContent != "" && p1.textContent != "" && p2.textContent != "" && p3.textContent != "" && p4.textContent != "" && p5.textContent != "" && p6.textContent != "" && p7.textContent != "" && p8.textContent != "") {
    message.textContent = ">> TIE <<";
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont00.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont00.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont00": () => (/* binding */ cont00)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont00() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p0 = document.querySelector('.mx-name-id_0');

  if (message.classList.contains('X') && p0.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.textContent = "X";
    document.querySelector('.mx-name-id_0').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p0.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_0').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont01.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont01.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont01": () => (/* binding */ cont01)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont01() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p1 = document.querySelector('.mx-name-id_1');

  if (message.classList.contains('X') && p1.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.textContent = "X";
    document.querySelector('.mx-name-id_1').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p1.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_1').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont02.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont02.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont02": () => (/* binding */ cont02)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont02() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p2 = document.querySelector('.mx-name-id_2');

  if (message.classList.contains('X') && p2.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.textContent = "X";
    document.querySelector('.mx-name-id_2').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p2.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_2').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont03.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont03.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont03": () => (/* binding */ cont03)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont03() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p3 = document.querySelector('.mx-name-id_3');

  if (message.classList.contains('X') && p3.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.innerText = "X";
    document.querySelector('.mx-name-id_3').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p3.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_3').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont04.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont04.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont04": () => (/* binding */ cont04)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont04() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p4 = document.querySelector('.mx-name-id_4');

  if (message.classList.contains('X') && p4.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.innerText = "X";
    document.querySelector('.mx-name-id_4').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p4.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_4').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont05.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont05.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont05": () => (/* binding */ cont05)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont05() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p5 = document.querySelector('.mx-name-id_5');

  if (message.classList.contains('X') && p5.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.innerText = "X";
    document.querySelector('.mx-name-id_5').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p5.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_5').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont06.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont06.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont06": () => (/* binding */ cont06)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont06() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p6 = document.querySelector('.mx-name-id_6');

  if (message.classList.contains('X') && p6.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.innerText = "X";
    document.querySelector('.mx-name-id_6').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p6.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_6').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont07.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont07.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont07": () => (/* binding */ cont07)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont07() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p7 = document.querySelector('.mx-name-id_7');

  if (message.classList.contains('X') && p7.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.innerText = "X";
    document.querySelector('.mx-name-id_7').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p7.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_7').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont08.js":
/*!**********************************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont08.js ***!
  \**********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "cont08": () => (/* binding */ cont08)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function cont08() {
  // BEGIN USER CODE
  var message = document.querySelector('.mx-name-msg_game');
  var PlayerX = document.createElement('X');
  var PlayerO = document.createElement('O');
  var p8 = document.querySelector('.mx-name-id_8');

  if (message.classList.contains('X') && p8.textContent === "") {
    message.textContent = "Player O turn";
    message.classList.remove('X');
    message.classList.add('O');
    PlayerX.innerText = "X";
    document.querySelector('.mx-name-id_8').appendChild(PlayerX);
  } else if (message.classList.contains('O') && p8.textContent === "") {
    message.textContent = "Player X turn";
    message.classList.remove('O');
    message.classList.add('X');
    PlayerO.innerText = "O";
    document.querySelector('.mx-name-id_8').appendChild(PlayerO);
  } // END USER CODE

}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!*************************************************************************************!*\
  !*** ../../../../../../Users/LSGH/Downloads/Games-main/deployment/tmp/jsactions.js ***!
  \*************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "MyFirstModule$cont00": () => (/* binding */ MyFirstModule$cont00),
/* harmony export */   "MyFirstModule$Validation": () => (/* binding */ MyFirstModule$Validation),
/* harmony export */   "MyFirstModule$cont01": () => (/* binding */ MyFirstModule$cont01),
/* harmony export */   "MyFirstModule$cont02": () => (/* binding */ MyFirstModule$cont02),
/* harmony export */   "MyFirstModule$cont03": () => (/* binding */ MyFirstModule$cont03),
/* harmony export */   "MyFirstModule$cont04": () => (/* binding */ MyFirstModule$cont04),
/* harmony export */   "MyFirstModule$cont05": () => (/* binding */ MyFirstModule$cont05),
/* harmony export */   "MyFirstModule$cont06": () => (/* binding */ MyFirstModule$cont06),
/* harmony export */   "MyFirstModule$cont07": () => (/* binding */ MyFirstModule$cont07),
/* harmony export */   "MyFirstModule$cont08": () => (/* binding */ MyFirstModule$cont08)
/* harmony export */ });
const MyFirstModule$cont00 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont00 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont00.js"))).cont00;
const MyFirstModule$Validation = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/Validation */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/Validation.js"))).Validation;
const MyFirstModule$cont01 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont01 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont01.js"))).cont01;
const MyFirstModule$cont02 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont02 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont02.js"))).cont02;
const MyFirstModule$cont03 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont03 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont03.js"))).cont03;
const MyFirstModule$cont04 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont04 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont04.js"))).cont04;
const MyFirstModule$cont05 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont05 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont05.js"))).cont05;
const MyFirstModule$cont06 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont06 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont06.js"))).cont06;
const MyFirstModule$cont07 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont07 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont07.js"))).cont07;
const MyFirstModule$cont08 = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont08 */ "../../../../../../Users/LSGH/Downloads/Games-main/javascriptsource/myfirstmodule/actions/cont08.js"))).cont08;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVDLFVBQWYsR0FBNEI7QUFDbEM7QUFDQSxNQUFJQyxPQUFPLEdBQUdDLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixtQkFBdkIsQ0FBZDtBQUNBLE1BQUlDLEVBQUUsR0FBR0YsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7QUFDQSxNQUFJRSxFQUFFLEdBQUdILFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixDQUFUO0FBQ0EsTUFBSUcsRUFBRSxHQUFHSixRQUFRLENBQUNDLGFBQVQsQ0FBdUIsZUFBdkIsQ0FBVDtBQUNBLE1BQUlJLEVBQUUsR0FBR0wsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7QUFDQSxNQUFJSyxFQUFFLEdBQUdOLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixDQUFUO0FBQ0EsTUFBSU0sRUFBRSxHQUFHUCxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsZUFBdkIsQ0FBVDtBQUNBLE1BQUlPLEVBQUUsR0FBR1IsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7QUFDQSxNQUFJUSxFQUFFLEdBQUdULFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixDQUFUO0FBQ0EsTUFBSVMsRUFBRSxHQUFHVixRQUFRLENBQUNDLGFBQVQsQ0FBdUIsZUFBdkIsQ0FBVDs7QUFFQSxNQUFJQyxFQUFFLENBQUNTLFdBQUgsS0FBa0IsR0FBbEIsSUFBeUJSLEVBQUUsQ0FBQ1EsV0FBSCxLQUFtQixHQUE1QyxJQUFvRFAsRUFBRSxDQUFDTyxXQUFILEtBQW1CLEdBQTNFLEVBQWlGO0FBQ2hGWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQSxHQUZELE1BRU8sSUFBSU4sRUFBRSxDQUFDTSxXQUFILEtBQWtCLEdBQWxCLElBQXlCTCxFQUFFLENBQUNLLFdBQUgsS0FBbUIsR0FBNUMsSUFBb0RKLEVBQUUsQ0FBQ0ksV0FBSCxLQUFtQixHQUEzRSxFQUFnRjtBQUN0RlosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0EsR0FGTSxNQUVBLElBQUlILEVBQUUsQ0FBQ0csV0FBSCxLQUFrQixHQUFsQixJQUF5QkYsRUFBRSxDQUFDRSxXQUFILEtBQW1CLEdBQTVDLElBQW9ERCxFQUFFLENBQUNDLFdBQUgsS0FBbUIsR0FBM0UsRUFBZ0Y7QUFDdEZaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBLEdBRk0sTUFFQSxJQUFJVCxFQUFFLENBQUNTLFdBQUgsS0FBa0IsR0FBbEIsSUFBeUJOLEVBQUUsQ0FBQ00sV0FBSCxLQUFtQixHQUE1QyxJQUFvREgsRUFBRSxDQUFDRyxXQUFILEtBQW1CLEdBQTNFLEVBQWdGO0FBQ3RGWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQSxHQUZNLE1BRUEsSUFBSVIsRUFBRSxDQUFDUSxXQUFILEtBQWtCLEdBQWxCLElBQXlCTCxFQUFFLENBQUNLLFdBQUgsS0FBbUIsR0FBNUMsSUFBb0RGLEVBQUUsQ0FBQ0UsV0FBSCxLQUFtQixHQUEzRSxFQUFnRjtBQUN0RlosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0EsR0FGTSxNQUVBLElBQUlQLEVBQUUsQ0FBQ08sV0FBSCxLQUFrQixHQUFsQixJQUF5QkosRUFBRSxDQUFDSSxXQUFILEtBQW1CLEdBQTVDLElBQW9ERCxFQUFFLENBQUNDLFdBQUgsS0FBbUIsR0FBM0UsRUFBZ0Y7QUFDdEZaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBLEdBRk0sTUFFQSxJQUFJVCxFQUFFLENBQUNTLFdBQUgsS0FBa0IsR0FBbEIsSUFBeUJMLEVBQUUsQ0FBQ0ssV0FBSCxLQUFtQixHQUE1QyxJQUFvREQsRUFBRSxDQUFDQyxXQUFILEtBQW1CLEdBQTNFLEVBQWdGO0FBQ3RGWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQSxHQUZNLE1BRUEsSUFBSVAsRUFBRSxDQUFDTyxXQUFILEtBQWtCLEdBQWxCLElBQXlCTCxFQUFFLENBQUNLLFdBQUgsS0FBbUIsR0FBNUMsSUFBb0RILEVBQUUsQ0FBQ0csV0FBSCxLQUFtQixHQUEzRSxFQUFnRjtBQUN0RlosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0EsR0FGTSxNQUVBLElBQUlULEVBQUUsQ0FBQ1MsV0FBSCxLQUFrQixHQUFsQixJQUF5QlIsRUFBRSxDQUFDUSxXQUFILEtBQW1CLEdBQTVDLElBQW9EUCxFQUFFLENBQUNPLFdBQUgsS0FBbUIsR0FBM0UsRUFBaUY7QUFDdkZaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBLEdBRk0sTUFFQSxJQUFJTixFQUFFLENBQUNNLFdBQUgsS0FBa0IsR0FBbEIsSUFBeUJMLEVBQUUsQ0FBQ0ssV0FBSCxLQUFtQixHQUE1QyxJQUFvREosRUFBRSxDQUFDSSxXQUFILEtBQW1CLEdBQTNFLEVBQWdGO0FBQ3RGWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQSxHQUZNLE1BRUEsSUFBSUgsRUFBRSxDQUFDRyxXQUFILEtBQWtCLEdBQWxCLElBQXlCRixFQUFFLENBQUNFLFdBQUgsS0FBbUIsR0FBNUMsSUFBb0RELEVBQUUsQ0FBQ0MsV0FBSCxLQUFtQixHQUEzRSxFQUFnRjtBQUN0RlosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0EsR0FGTSxNQUVBLElBQUlULEVBQUUsQ0FBQ1MsV0FBSCxLQUFrQixHQUFsQixJQUF5Qk4sRUFBRSxDQUFDTSxXQUFILEtBQW1CLEdBQTVDLElBQW9ESCxFQUFFLENBQUNHLFdBQUgsS0FBbUIsR0FBM0UsRUFBZ0Y7QUFDdEZaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBLEdBRk0sTUFFQSxJQUFJUixFQUFFLENBQUNRLFdBQUgsS0FBa0IsR0FBbEIsSUFBeUJMLEVBQUUsQ0FBQ0ssV0FBSCxLQUFtQixHQUE1QyxJQUFvREYsRUFBRSxDQUFDRSxXQUFILEtBQW1CLEdBQTNFLEVBQWdGO0FBQ3RGWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQSxHQUZNLE1BRUEsSUFBSVAsRUFBRSxDQUFDTyxXQUFILEtBQWtCLEdBQWxCLElBQXlCSixFQUFFLENBQUNJLFdBQUgsS0FBbUIsR0FBNUMsSUFBb0RELEVBQUUsQ0FBQ0MsV0FBSCxLQUFtQixHQUEzRSxFQUFnRjtBQUN0RlosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0EsR0FGTSxNQUVBLElBQUlULEVBQUUsQ0FBQ1MsV0FBSCxLQUFrQixHQUFsQixJQUF5QkwsRUFBRSxDQUFDSyxXQUFILEtBQW1CLEdBQTVDLElBQW9ERCxFQUFFLENBQUNDLFdBQUgsS0FBbUIsR0FBM0UsRUFBZ0Y7QUFDdEZaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBLEdBRk0sTUFFQSxJQUFJUCxFQUFFLENBQUNPLFdBQUgsS0FBa0IsR0FBbEIsSUFBeUJMLEVBQUUsQ0FBQ0ssV0FBSCxLQUFtQixHQUE1QyxJQUFvREgsRUFBRSxDQUFDRyxXQUFILEtBQW1CLEdBQTNFLEVBQWdGO0FBQ3RGWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQSxHQUZNLE1BRUEsSUFBSVQsRUFBRSxDQUFDUyxXQUFILElBQWtCLEVBQWxCLElBQXdCUixFQUFFLENBQUNRLFdBQUgsSUFBa0IsRUFBMUMsSUFBZ0RQLEVBQUUsQ0FBQ08sV0FBSCxJQUFrQixFQUFsRSxJQUF3RU4sRUFBRSxDQUFDTSxXQUFILElBQWtCLEVBQTFGLElBQ1JMLEVBQUUsQ0FBQ0ssV0FBSCxJQUFrQixFQURWLElBQ2dCSixFQUFFLENBQUNJLFdBQUgsSUFBa0IsRUFEbEMsSUFDd0NILEVBQUUsQ0FBQ0csV0FBSCxJQUFrQixFQUQxRCxJQUNnRUYsRUFBRSxDQUFDRSxXQUFILElBQWtCLEVBRGxGLElBQ3dGRCxFQUFFLENBQUNDLFdBQUgsSUFBa0IsRUFEOUcsRUFDa0g7QUFDeEhaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixXQUF0QjtBQUNBLEdBaERpQyxDQWtEbEM7O0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7QUNsRUQ7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQyxNQUFmLEdBQXdCO0FBQzlCO0FBQ0EsTUFBSWIsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlaLEVBQUUsR0FBR0YsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNmLEVBQUUsQ0FBQ1MsV0FBSCxLQUFtQixFQUEzRCxFQUFnRTtBQUMvRFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNGLFdBQVIsR0FBc0IsR0FBdEI7QUFDQVgsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RQLE9BQXBEO0FBQ0EsR0FORCxNQU1PLElBQUlkLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JDLFFBQWxCLENBQTJCLEdBQTNCLEtBQW1DZixFQUFFLENBQUNTLFdBQUgsS0FBbUIsRUFBMUQsRUFBOEQ7QUFDcEVaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBWixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRSxNQUFsQixDQUF5QixHQUF6QjtBQUNBbkIsSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkcsR0FBbEIsQ0FBc0IsR0FBdEI7QUFDQUosSUFBQUEsT0FBTyxDQUFDTSxTQUFSLEdBQW9CLEdBQXBCO0FBQ0FyQixJQUFBQSxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsZUFBdkIsRUFBd0NtQixXQUF4QyxDQUFvREwsT0FBcEQ7QUFDQSxHQW5CNkIsQ0FvQjlCOztBQUNBOzs7Ozs7Ozs7Ozs7Ozs7O0FDcENEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZU8sTUFBZixHQUF3QjtBQUM5QjtBQUNBLE1BQUl2QixPQUFPLEdBQUdDLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixtQkFBdkIsQ0FBZDtBQUNBLE1BQUlZLE9BQU8sR0FBR2IsUUFBUSxDQUFDYyxhQUFULENBQXVCLEdBQXZCLENBQWQ7QUFDQSxNQUFJQyxPQUFPLEdBQUdmLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSVgsRUFBRSxHQUFHSCxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsZUFBdkIsQ0FBVDs7QUFFQSxNQUFLRixPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ2QsRUFBRSxDQUFDUSxXQUFILEtBQW1CLEVBQTNELEVBQWlFO0FBQ2hFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FOLElBQUFBLE9BQU8sQ0FBQ0YsV0FBUixHQUFzQixHQUF0QjtBQUNBWCxJQUFBQSxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsZUFBdkIsRUFBd0NtQixXQUF4QyxDQUFvRFAsT0FBcEQ7QUFDQSxHQU5ELE1BTU8sSUFBSWQsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNkLEVBQUUsQ0FBQ1EsV0FBSCxLQUFtQixFQUExRCxFQUFnRTtBQUN0RVosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBSixJQUFBQSxPQUFPLENBQUNNLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9ETCxPQUFwRDtBQUNBLEdBbkI2QixDQW9COUI7O0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7QUNwQ0Q7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlUSxNQUFmLEdBQXdCO0FBQzlCO0FBQ0EsTUFBSXhCLE9BQU8sR0FBR0MsUUFBUSxDQUFDQyxhQUFULENBQXVCLG1CQUF2QixDQUFkO0FBQ0EsTUFBSVksT0FBTyxHQUFHYixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlDLE9BQU8sR0FBR2YsUUFBUSxDQUFDYyxhQUFULENBQXVCLEdBQXZCLENBQWQ7QUFDQSxNQUFJVixFQUFFLEdBQUdKLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixDQUFUOztBQUVBLE1BQUtGLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JDLFFBQWxCLENBQTJCLEdBQTNCLEtBQW1DYixFQUFFLENBQUNPLFdBQUgsS0FBbUIsRUFBM0QsRUFBZ0U7QUFDL0RaLElBQUFBLE9BQU8sQ0FBQ1ksV0FBUixHQUFzQixlQUF0QjtBQUNBWixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRSxNQUFsQixDQUF5QixHQUF6QjtBQUNBbkIsSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkcsR0FBbEIsQ0FBc0IsR0FBdEI7QUFDQU4sSUFBQUEsT0FBTyxDQUFDRixXQUFSLEdBQXNCLEdBQXRCO0FBQ0FYLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ2IsRUFBRSxDQUFDTyxXQUFILEtBQW1CLEVBQTFELEVBQWdFO0FBQ3RFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7Ozs7Ozs7OztBQ3BDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVTLE1BQWYsR0FBd0I7QUFDOUI7QUFDQSxNQUFJekIsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlULEVBQUUsR0FBR0wsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNaLEVBQUUsQ0FBQ00sV0FBSCxLQUFtQixFQUEzRCxFQUErRDtBQUM5RFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNRLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ1osRUFBRSxDQUFDTSxXQUFILEtBQW1CLEVBQTFELEVBQThEO0FBQ3BFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7Ozs7Ozs7OztBQ3BDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVVLE1BQWYsR0FBd0I7QUFDOUI7QUFDQSxNQUFJMUIsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlSLEVBQUUsR0FBR04sUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNYLEVBQUUsQ0FBQ0ssV0FBSCxLQUFtQixFQUEzRCxFQUFnRTtBQUMvRFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNRLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ1gsRUFBRSxDQUFDSyxXQUFILEtBQW1CLEVBQTFELEVBQThEO0FBQ3BFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7Ozs7Ozs7OztBQ3BDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVXLE1BQWYsR0FBd0I7QUFDOUI7QUFDQSxNQUFJM0IsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlQLEVBQUUsR0FBR1AsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNWLEVBQUUsQ0FBQ0ksV0FBSCxLQUFtQixFQUEzRCxFQUErRDtBQUM5RFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNRLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ1YsRUFBRSxDQUFDSSxXQUFILEtBQW1CLEVBQTFELEVBQStEO0FBQ3JFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7Ozs7Ozs7OztBQ3BDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVZLE1BQWYsR0FBd0I7QUFDOUI7QUFDQSxNQUFJNUIsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlOLEVBQUUsR0FBR1IsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNULEVBQUUsQ0FBQ0csV0FBSCxLQUFtQixFQUEzRCxFQUErRDtBQUM5RFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNRLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ1QsRUFBRSxDQUFDRyxXQUFILEtBQW1CLEVBQTFELEVBQThEO0FBQ3BFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7Ozs7Ozs7OztBQ3BDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVhLE1BQWYsR0FBd0I7QUFDOUI7QUFDQSxNQUFJN0IsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlMLEVBQUUsR0FBR1QsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNSLEVBQUUsQ0FBQ0UsV0FBSCxLQUFtQixFQUEzRCxFQUFnRTtBQUMvRFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNRLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ1IsRUFBRSxDQUFDRSxXQUFILEtBQW1CLEVBQTFELEVBQThEO0FBQ3BFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7Ozs7Ozs7OztBQ3BDRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVjLE1BQWYsR0FBd0I7QUFDOUI7QUFDQSxNQUFJOUIsT0FBTyxHQUFHQyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsbUJBQXZCLENBQWQ7QUFDQSxNQUFJWSxPQUFPLEdBQUdiLFFBQVEsQ0FBQ2MsYUFBVCxDQUF1QixHQUF2QixDQUFkO0FBQ0EsTUFBSUMsT0FBTyxHQUFHZixRQUFRLENBQUNjLGFBQVQsQ0FBdUIsR0FBdkIsQ0FBZDtBQUNBLE1BQUlKLEVBQUUsR0FBR1YsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLENBQVQ7O0FBRUEsTUFBS0YsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkMsUUFBbEIsQ0FBMkIsR0FBM0IsS0FBbUNQLEVBQUUsQ0FBQ0MsV0FBSCxLQUFtQixFQUEzRCxFQUFnRTtBQUMvRFosSUFBQUEsT0FBTyxDQUFDWSxXQUFSLEdBQXNCLGVBQXRCO0FBQ0FaLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JFLE1BQWxCLENBQXlCLEdBQXpCO0FBQ0FuQixJQUFBQSxPQUFPLENBQUNpQixTQUFSLENBQWtCRyxHQUFsQixDQUFzQixHQUF0QjtBQUNBTixJQUFBQSxPQUFPLENBQUNRLFNBQVIsR0FBb0IsR0FBcEI7QUFDQXJCLElBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixlQUF2QixFQUF3Q21CLFdBQXhDLENBQW9EUCxPQUFwRDtBQUNBLEdBTkQsTUFNTyxJQUFJZCxPQUFPLENBQUNpQixTQUFSLENBQWtCQyxRQUFsQixDQUEyQixHQUEzQixLQUFtQ1AsRUFBRSxDQUFDQyxXQUFILEtBQW1CLEVBQTFELEVBQStEO0FBQ3JFWixJQUFBQSxPQUFPLENBQUNZLFdBQVIsR0FBc0IsZUFBdEI7QUFDQVosSUFBQUEsT0FBTyxDQUFDaUIsU0FBUixDQUFrQkUsTUFBbEIsQ0FBeUIsR0FBekI7QUFDQW5CLElBQUFBLE9BQU8sQ0FBQ2lCLFNBQVIsQ0FBa0JHLEdBQWxCLENBQXNCLEdBQXRCO0FBQ0FKLElBQUFBLE9BQU8sQ0FBQ00sU0FBUixHQUFvQixHQUFwQjtBQUNBckIsSUFBQUEsUUFBUSxDQUFDQyxhQUFULENBQXVCLGVBQXZCLEVBQXdDbUIsV0FBeEMsQ0FBb0RMLE9BQXBEO0FBQ0EsR0FuQjZCLENBb0I5Qjs7QUFDQTs7Ozs7Ozs7OztBQ3BDRDs7Ozs7O1VDQUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTs7VUFFQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTs7Ozs7V0N0QkE7V0FDQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLGlDQUFpQyxXQUFXO1dBQzVDO1dBQ0E7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx5Q0FBeUMsd0NBQXdDO1dBQ2pGO1dBQ0E7V0FDQTs7Ozs7V0NQQTs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSx1REFBdUQsaUJBQWlCO1dBQ3hFO1dBQ0EsZ0RBQWdELGFBQWE7V0FDN0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDTk8sTUFBTWUsb0JBQW9CLEdBQUcsWUFBWSxDQUFDLE1BQU0saVNBQVAsRUFBbUdsQixNQUE1STtBQUNBLE1BQU1tQix3QkFBd0IsR0FBRyxZQUFZLENBQUMsTUFBTSx5U0FBUCxFQUF1R2pDLFVBQXBKO0FBQ0EsTUFBTWtDLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1STtBQUNBLE1BQU1XLG9CQUFvQixHQUFHLFlBQVksQ0FBQyxNQUFNLGlTQUFQLEVBQW1HVixNQUE1SSxDIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvVmFsaWRhdGlvbi5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvTFNHSC9Eb3dubG9hZHMvR2FtZXMtbWFpbi9qYXZhc2NyaXB0c291cmNlL215Zmlyc3Rtb2R1bGUvYWN0aW9ucy9jb250MDAuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDAxLmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL2NvbnQwMi5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvTFNHSC9Eb3dubG9hZHMvR2FtZXMtbWFpbi9qYXZhc2NyaXB0c291cmNlL215Zmlyc3Rtb2R1bGUvYWN0aW9ucy9jb250MDMuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDA0LmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL2NvbnQwNS5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvTFNHSC9Eb3dubG9hZHMvR2FtZXMtbWFpbi9qYXZhc2NyaXB0c291cmNlL215Zmlyc3Rtb2R1bGUvYWN0aW9ucy9jb250MDYuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDA3LmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL2NvbnQwOC5qcyIsIndlYnBhY2s6Ly8vZXh0ZXJuYWwgYW1kIFwiYmlnLmpzXCIiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svYm9vdHN0cmFwIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvY29tcGF0IGdldCBkZWZhdWx0IGV4cG9ydCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2RlZmluZSBwcm9wZXJ0eSBnZXR0ZXJzIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvaGFzT3duUHJvcGVydHkgc2hvcnRoYW5kIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvbWFrZSBuYW1lc3BhY2Ugb2JqZWN0Iiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2RlcGxveW1lbnQvdG1wL2pzYWN0aW9ucy5qcyJdLCJzb3VyY2VzQ29udGVudCI6WyIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIFZhbGlkYXRpb24oKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0dmFyIG1lc3NhZ2UgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1tc2dfZ2FtZScpXHJcblx0dmFyIHAwID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMCcpXHJcblx0dmFyIHAxID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMScpXHJcblx0dmFyIHAyID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMicpXHJcblx0dmFyIHAzID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMycpXHJcblx0dmFyIHA0ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNCcpXHJcblx0dmFyIHA1ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNScpXHJcblx0dmFyIHA2ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNicpXHJcblx0dmFyIHA3ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNycpXHJcblx0dmFyIHA4ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfOCcpXHJcblxyXG5cdGlmIChwMC50ZXh0Q29udGVudCA9PT1cIlhcIiAmJiBwMS50ZXh0Q29udGVudCA9PT0gXCJYXCIgICYmIHAyLnRleHRDb250ZW50ID09PSBcIlhcIiApIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDMudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDQudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwNS50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDYudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDcudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwOC50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDAudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDMudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwNi50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDEudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDQudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwNy50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDIudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDUudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwOC50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDAudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDQudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwOC50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDIudGV4dENvbnRlbnQgPT09XCJYXCIgJiYgcDQudGV4dENvbnRlbnQgPT09IFwiWFwiICAmJiBwNi50ZXh0Q29udGVudCA9PT0gXCJYXCIgKXtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBMQVlFUiBYIFdJTiFcIlxyXG5cdH0gZWxzZSBpZiAocDAudGV4dENvbnRlbnQgPT09XCJPXCIgJiYgcDEudGV4dENvbnRlbnQgPT09IFwiT1wiICAmJiBwMi50ZXh0Q29udGVudCA9PT0gXCJPXCIgKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAzLnRleHRDb250ZW50ID09PVwiT1wiICYmIHA0LnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDUudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHA2LnRleHRDb250ZW50ID09PVwiT1wiICYmIHA3LnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDgudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAwLnRleHRDb250ZW50ID09PVwiT1wiICYmIHAzLnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDYudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAxLnRleHRDb250ZW50ID09PVwiT1wiICYmIHA0LnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDcudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAyLnRleHRDb250ZW50ID09PVwiT1wiICYmIHA1LnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDgudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAwLnRleHRDb250ZW50ID09PVwiT1wiICYmIHA0LnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDgudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAyLnRleHRDb250ZW50ID09PVwiT1wiICYmIHA0LnRleHRDb250ZW50ID09PSBcIk9cIiAgJiYgcDYudGV4dENvbnRlbnQgPT09IFwiT1wiICl7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQTEFZRVIgTyBXSU4hXCJcclxuXHR9IGVsc2UgaWYgKHAwLnRleHRDb250ZW50ICE9IFwiXCIgJiYgcDEudGV4dENvbnRlbnQgIT0gXCJcIiAmJiBwMi50ZXh0Q29udGVudCAhPSBcIlwiICYmIHAzLnRleHRDb250ZW50ICE9IFwiXCIgXHJcblx0JiYgcDQudGV4dENvbnRlbnQgIT0gXCJcIiAmJiBwNS50ZXh0Q29udGVudCAhPSBcIlwiICYmIHA2LnRleHRDb250ZW50ICE9IFwiXCIgJiYgcDcudGV4dENvbnRlbnQgIT0gXCJcIiAmJiBwOC50ZXh0Q29udGVudCAhPSBcIlwiKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCI+PiBUSUUgPDxcIlxyXG5cdH1cclxuXHRcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBjb250MDAoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0dmFyIG1lc3NhZ2UgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1tc2dfZ2FtZScpXHJcblx0dmFyIFBsYXllclggPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdYJylcclxuXHR2YXIgUGxheWVyTyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ08nKVxyXG5cdHZhciBwMCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzAnKVxyXG5cclxuXHRpZiAoIG1lc3NhZ2UuY2xhc3NMaXN0LmNvbnRhaW5zKCdYJykgJiYgcDAudGV4dENvbnRlbnQgPT09IFwiXCIgKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQbGF5ZXIgTyB0dXJuXCJcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LnJlbW92ZSgnWCcpXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5hZGQoJ08nKVxyXG5cdFx0UGxheWVyWC50ZXh0Q29udGVudCA9IFwiWFwiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMCcpLmFwcGVuZENoaWxkKFBsYXllclgpO1xyXG5cdH0gZWxzZSBpZiAobWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ08nKSAmJiBwMC50ZXh0Q29udGVudCA9PT0gXCJcIikge1xyXG5cdFx0bWVzc2FnZS50ZXh0Q29udGVudCA9IFwiUGxheWVyIFggdHVyblwiXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5yZW1vdmUoJ08nKVxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QuYWRkKCdYJyk7XHJcblx0XHRQbGF5ZXJPLmlubmVyVGV4dCA9IFwiT1wiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMCcpLmFwcGVuZENoaWxkKFBsYXllck8pO1xyXG5cdH1cclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBjb250MDEoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0dmFyIG1lc3NhZ2UgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1tc2dfZ2FtZScpXHJcblx0dmFyIFBsYXllclggPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdYJylcclxuXHR2YXIgUGxheWVyTyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ08nKVxyXG5cdHZhciBwMSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzEnKVxyXG5cclxuXHRpZiAoIG1lc3NhZ2UuY2xhc3NMaXN0LmNvbnRhaW5zKCdYJykgJiYgcDEudGV4dENvbnRlbnQgPT09IFwiXCIgICkge1xyXG5cdFx0bWVzc2FnZS50ZXh0Q29udGVudCA9IFwiUGxheWVyIE8gdHVyblwiXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5yZW1vdmUoJ1gnKVxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QuYWRkKCdPJylcclxuXHRcdFBsYXllclgudGV4dENvbnRlbnQgPSBcIlhcIjtcclxuXHRcdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzEnKS5hcHBlbmRDaGlsZChQbGF5ZXJYKTtcclxuXHR9IGVsc2UgaWYgKG1lc3NhZ2UuY2xhc3NMaXN0LmNvbnRhaW5zKCdPJykgJiYgcDEudGV4dENvbnRlbnQgPT09IFwiXCIgICkge1xyXG5cdFx0bWVzc2FnZS50ZXh0Q29udGVudCA9IFwiUGxheWVyIFggdHVyblwiXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5yZW1vdmUoJ08nKVxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QuYWRkKCdYJyk7XHJcblx0XHRQbGF5ZXJPLmlubmVyVGV4dCA9IFwiT1wiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMScpLmFwcGVuZENoaWxkKFBsYXllck8pO1xyXG5cdH1cclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBjb250MDIoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0dmFyIG1lc3NhZ2UgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1tc2dfZ2FtZScpXHJcblx0dmFyIFBsYXllclggPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdYJylcclxuXHR2YXIgUGxheWVyTyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ08nKVxyXG5cdHZhciBwMiA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzInKVxyXG5cclxuXHRpZiAoIG1lc3NhZ2UuY2xhc3NMaXN0LmNvbnRhaW5zKCdYJykgJiYgcDIudGV4dENvbnRlbnQgPT09IFwiXCIgKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQbGF5ZXIgTyB0dXJuXCJcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LnJlbW92ZSgnWCcpXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5hZGQoJ08nKVxyXG5cdFx0UGxheWVyWC50ZXh0Q29udGVudCA9IFwiWFwiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMicpLmFwcGVuZENoaWxkKFBsYXllclgpO1xyXG5cdH0gZWxzZSBpZiAobWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ08nKSAmJiBwMi50ZXh0Q29udGVudCA9PT0gXCJcIiAgKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQbGF5ZXIgWCB0dXJuXCJcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LnJlbW92ZSgnTycpXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5hZGQoJ1gnKTtcclxuXHRcdFBsYXllck8uaW5uZXJUZXh0ID0gXCJPXCI7XHJcblx0XHRkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF8yJykuYXBwZW5kQ2hpbGQoUGxheWVyTyk7XHJcblx0fVxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGNvbnQwMygpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHR2YXIgbWVzc2FnZSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLW1zZ19nYW1lJylcclxuXHR2YXIgUGxheWVyWCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ1gnKVxyXG5cdHZhciBQbGF5ZXJPID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnTycpXHJcblx0dmFyIHAzID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfMycpXHJcblxyXG5cdGlmICggbWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ1gnKSAmJiBwMy50ZXh0Q29udGVudCA9PT0gXCJcIikge1xyXG5cdFx0bWVzc2FnZS50ZXh0Q29udGVudCA9IFwiUGxheWVyIE8gdHVyblwiXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5yZW1vdmUoJ1gnKVxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QuYWRkKCdPJylcclxuXHRcdFBsYXllclguaW5uZXJUZXh0ID0gXCJYXCI7XHJcblx0XHRkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF8zJykuYXBwZW5kQ2hpbGQoUGxheWVyWCk7XHJcblx0fSBlbHNlIGlmIChtZXNzYWdlLmNsYXNzTGlzdC5jb250YWlucygnTycpICYmIHAzLnRleHRDb250ZW50ID09PSBcIlwiKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQbGF5ZXIgWCB0dXJuXCJcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LnJlbW92ZSgnTycpXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5hZGQoJ1gnKTtcclxuXHRcdFBsYXllck8uaW5uZXJUZXh0ID0gXCJPXCI7XHJcblx0XHRkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF8zJykuYXBwZW5kQ2hpbGQoUGxheWVyTyk7XHJcblx0fVxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGNvbnQwNCgpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHR2YXIgbWVzc2FnZSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLW1zZ19nYW1lJylcclxuXHR2YXIgUGxheWVyWCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ1gnKVxyXG5cdHZhciBQbGF5ZXJPID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnTycpXHJcblx0dmFyIHA0ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNCcpXHJcblxyXG5cdGlmICggbWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ1gnKSAmJiBwNC50ZXh0Q29udGVudCA9PT0gXCJcIiApIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBsYXllciBPIHR1cm5cIlxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QucmVtb3ZlKCdYJylcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LmFkZCgnTycpXHJcblx0XHRQbGF5ZXJYLmlubmVyVGV4dCA9IFwiWFwiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNCcpLmFwcGVuZENoaWxkKFBsYXllclgpO1xyXG5cdH0gZWxzZSBpZiAobWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ08nKSAmJiBwNC50ZXh0Q29udGVudCA9PT0gXCJcIikge1xyXG5cdFx0bWVzc2FnZS50ZXh0Q29udGVudCA9IFwiUGxheWVyIFggdHVyblwiXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5yZW1vdmUoJ08nKVxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QuYWRkKCdYJyk7XHJcblx0XHRQbGF5ZXJPLmlubmVyVGV4dCA9IFwiT1wiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNCcpLmFwcGVuZENoaWxkKFBsYXllck8pO1xyXG5cdH1cclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBjb250MDUoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0dmFyIG1lc3NhZ2UgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1tc2dfZ2FtZScpXHJcblx0dmFyIFBsYXllclggPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdYJylcclxuXHR2YXIgUGxheWVyTyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ08nKVxyXG5cdHZhciBwNSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzUnKVxyXG5cclxuXHRpZiAoIG1lc3NhZ2UuY2xhc3NMaXN0LmNvbnRhaW5zKCdYJykgJiYgcDUudGV4dENvbnRlbnQgPT09IFwiXCIpIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBsYXllciBPIHR1cm5cIlxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QucmVtb3ZlKCdYJylcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LmFkZCgnTycpXHJcblx0XHRQbGF5ZXJYLmlubmVyVGV4dCA9IFwiWFwiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfNScpLmFwcGVuZENoaWxkKFBsYXllclgpO1xyXG5cdH0gZWxzZSBpZiAobWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ08nKSAmJiBwNS50ZXh0Q29udGVudCA9PT0gXCJcIiApIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBsYXllciBYIHR1cm5cIlxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QucmVtb3ZlKCdPJylcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LmFkZCgnWCcpO1xyXG5cdFx0UGxheWVyTy5pbm5lclRleHQgPSBcIk9cIjtcclxuXHRcdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzUnKS5hcHBlbmRDaGlsZChQbGF5ZXJPKTtcclxuXHR9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gY29udDA2KCkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdHZhciBtZXNzYWdlID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtbXNnX2dhbWUnKVxyXG5cdHZhciBQbGF5ZXJYID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnWCcpXHJcblx0dmFyIFBsYXllck8gPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdPJylcclxuXHR2YXIgcDYgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF82JylcclxuXHJcblx0aWYgKCBtZXNzYWdlLmNsYXNzTGlzdC5jb250YWlucygnWCcpICYmIHA2LnRleHRDb250ZW50ID09PSBcIlwiKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQbGF5ZXIgTyB0dXJuXCJcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LnJlbW92ZSgnWCcpXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5hZGQoJ08nKVxyXG5cdFx0UGxheWVyWC5pbm5lclRleHQgPSBcIlhcIjtcclxuXHRcdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzYnKS5hcHBlbmRDaGlsZChQbGF5ZXJYKTtcclxuXHR9IGVsc2UgaWYgKG1lc3NhZ2UuY2xhc3NMaXN0LmNvbnRhaW5zKCdPJykgJiYgcDYudGV4dENvbnRlbnQgPT09IFwiXCIpIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBsYXllciBYIHR1cm5cIlxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QucmVtb3ZlKCdPJylcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LmFkZCgnWCcpO1xyXG5cdFx0UGxheWVyTy5pbm5lclRleHQgPSBcIk9cIjtcclxuXHRcdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzYnKS5hcHBlbmRDaGlsZChQbGF5ZXJPKTtcclxuXHR9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gY29udDA3KCkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdHZhciBtZXNzYWdlID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtbXNnX2dhbWUnKVxyXG5cdHZhciBQbGF5ZXJYID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnWCcpXHJcblx0dmFyIFBsYXllck8gPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdPJylcclxuXHR2YXIgcDcgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF83JylcclxuXHJcblx0aWYgKCBtZXNzYWdlLmNsYXNzTGlzdC5jb250YWlucygnWCcpICYmIHA3LnRleHRDb250ZW50ID09PSBcIlwiICkge1xyXG5cdFx0bWVzc2FnZS50ZXh0Q29udGVudCA9IFwiUGxheWVyIE8gdHVyblwiXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5yZW1vdmUoJ1gnKVxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QuYWRkKCdPJylcclxuXHRcdFBsYXllclguaW5uZXJUZXh0ID0gXCJYXCI7XHJcblx0XHRkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF83JykuYXBwZW5kQ2hpbGQoUGxheWVyWCk7XHJcblx0fSBlbHNlIGlmIChtZXNzYWdlLmNsYXNzTGlzdC5jb250YWlucygnTycpICYmIHA3LnRleHRDb250ZW50ID09PSBcIlwiKSB7XHJcblx0XHRtZXNzYWdlLnRleHRDb250ZW50ID0gXCJQbGF5ZXIgWCB0dXJuXCJcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LnJlbW92ZSgnTycpXHJcblx0XHRtZXNzYWdlLmNsYXNzTGlzdC5hZGQoJ1gnKTtcclxuXHRcdFBsYXllck8uaW5uZXJUZXh0ID0gXCJPXCI7XHJcblx0XHRkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubXgtbmFtZS1pZF83JykuYXBwZW5kQ2hpbGQoUGxheWVyTyk7XHJcblx0fVxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGNvbnQwOCgpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHR2YXIgbWVzc2FnZSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLW1zZ19nYW1lJylcclxuXHR2YXIgUGxheWVyWCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ1gnKVxyXG5cdHZhciBQbGF5ZXJPID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnTycpXHJcblx0dmFyIHA4ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfOCcpXHJcblxyXG5cdGlmICggbWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ1gnKSAmJiBwOC50ZXh0Q29udGVudCA9PT0gXCJcIiApIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBsYXllciBPIHR1cm5cIlxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QucmVtb3ZlKCdYJylcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LmFkZCgnTycpXHJcblx0XHRQbGF5ZXJYLmlubmVyVGV4dCA9IFwiWFwiO1xyXG5cdFx0ZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLm14LW5hbWUtaWRfOCcpLmFwcGVuZENoaWxkKFBsYXllclgpO1xyXG5cdH0gZWxzZSBpZiAobWVzc2FnZS5jbGFzc0xpc3QuY29udGFpbnMoJ08nKSAmJiBwOC50ZXh0Q29udGVudCA9PT0gXCJcIiApIHtcclxuXHRcdG1lc3NhZ2UudGV4dENvbnRlbnQgPSBcIlBsYXllciBYIHR1cm5cIlxyXG5cdFx0bWVzc2FnZS5jbGFzc0xpc3QucmVtb3ZlKCdPJylcclxuXHRcdG1lc3NhZ2UuY2xhc3NMaXN0LmFkZCgnWCcpO1xyXG5cdFx0UGxheWVyTy5pbm5lclRleHQgPSBcIk9cIjtcclxuXHRcdGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5teC1uYW1lLWlkXzgnKS5hcHBlbmRDaGlsZChQbGF5ZXJPKTtcclxuXHR9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIm1vZHVsZS5leHBvcnRzID0gX19XRUJQQUNLX0VYVEVSTkFMX01PRFVMRV9iaWdfanNfXzsiLCIvLyBUaGUgbW9kdWxlIGNhY2hlXG52YXIgX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fID0ge307XG5cbi8vIFRoZSByZXF1aXJlIGZ1bmN0aW9uXG5mdW5jdGlvbiBfX3dlYnBhY2tfcmVxdWlyZV9fKG1vZHVsZUlkKSB7XG5cdC8vIENoZWNrIGlmIG1vZHVsZSBpcyBpbiBjYWNoZVxuXHR2YXIgY2FjaGVkTW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXTtcblx0aWYgKGNhY2hlZE1vZHVsZSAhPT0gdW5kZWZpbmVkKSB7XG5cdFx0cmV0dXJuIGNhY2hlZE1vZHVsZS5leHBvcnRzO1xuXHR9XG5cdC8vIENyZWF0ZSBhIG5ldyBtb2R1bGUgKGFuZCBwdXQgaXQgaW50byB0aGUgY2FjaGUpXG5cdHZhciBtb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdID0ge1xuXHRcdC8vIG5vIG1vZHVsZS5pZCBuZWVkZWRcblx0XHQvLyBubyBtb2R1bGUubG9hZGVkIG5lZWRlZFxuXHRcdGV4cG9ydHM6IHt9XG5cdH07XG5cblx0Ly8gRXhlY3V0ZSB0aGUgbW9kdWxlIGZ1bmN0aW9uXG5cdF9fd2VicGFja19tb2R1bGVzX19bbW9kdWxlSWRdKG1vZHVsZSwgbW9kdWxlLmV4cG9ydHMsIF9fd2VicGFja19yZXF1aXJlX18pO1xuXG5cdC8vIFJldHVybiB0aGUgZXhwb3J0cyBvZiB0aGUgbW9kdWxlXG5cdHJldHVybiBtb2R1bGUuZXhwb3J0cztcbn1cblxuIiwiLy8gZ2V0RGVmYXVsdEV4cG9ydCBmdW5jdGlvbiBmb3IgY29tcGF0aWJpbGl0eSB3aXRoIG5vbi1oYXJtb255IG1vZHVsZXNcbl9fd2VicGFja19yZXF1aXJlX18ubiA9IChtb2R1bGUpID0+IHtcblx0dmFyIGdldHRlciA9IG1vZHVsZSAmJiBtb2R1bGUuX19lc01vZHVsZSA/XG5cdFx0KCkgPT4gKG1vZHVsZVsnZGVmYXVsdCddKSA6XG5cdFx0KCkgPT4gKG1vZHVsZSk7XG5cdF9fd2VicGFja19yZXF1aXJlX18uZChnZXR0ZXIsIHsgYTogZ2V0dGVyIH0pO1xuXHRyZXR1cm4gZ2V0dGVyO1xufTsiLCIvLyBkZWZpbmUgZ2V0dGVyIGZ1bmN0aW9ucyBmb3IgaGFybW9ueSBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLmQgPSAoZXhwb3J0cywgZGVmaW5pdGlvbikgPT4ge1xuXHRmb3IodmFyIGtleSBpbiBkZWZpbml0aW9uKSB7XG5cdFx0aWYoX193ZWJwYWNrX3JlcXVpcmVfXy5vKGRlZmluaXRpb24sIGtleSkgJiYgIV9fd2VicGFja19yZXF1aXJlX18ubyhleHBvcnRzLCBrZXkpKSB7XG5cdFx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywga2V5LCB7IGVudW1lcmFibGU6IHRydWUsIGdldDogZGVmaW5pdGlvbltrZXldIH0pO1xuXHRcdH1cblx0fVxufTsiLCJfX3dlYnBhY2tfcmVxdWlyZV9fLm8gPSAob2JqLCBwcm9wKSA9PiAoT2JqZWN0LnByb3RvdHlwZS5oYXNPd25Qcm9wZXJ0eS5jYWxsKG9iaiwgcHJvcCkpIiwiLy8gZGVmaW5lIF9fZXNNb2R1bGUgb24gZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5yID0gKGV4cG9ydHMpID0+IHtcblx0aWYodHlwZW9mIFN5bWJvbCAhPT0gJ3VuZGVmaW5lZCcgJiYgU3ltYm9sLnRvU3RyaW5nVGFnKSB7XG5cdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIFN5bWJvbC50b1N0cmluZ1RhZywgeyB2YWx1ZTogJ01vZHVsZScgfSk7XG5cdH1cblx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICdfX2VzTW9kdWxlJywgeyB2YWx1ZTogdHJ1ZSB9KTtcbn07IiwiZXhwb3J0IGNvbnN0IE15Rmlyc3RNb2R1bGUkY29udDAwID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDAwXCIpKS5jb250MDA7XG5leHBvcnQgY29uc3QgTXlGaXJzdE1vZHVsZSRWYWxpZGF0aW9uID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvVmFsaWRhdGlvblwiKSkuVmFsaWRhdGlvbjtcbmV4cG9ydCBjb25zdCBNeUZpcnN0TW9kdWxlJGNvbnQwMSA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL2NvbnQwMVwiKSkuY29udDAxO1xuZXhwb3J0IGNvbnN0IE15Rmlyc3RNb2R1bGUkY29udDAyID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDAyXCIpKS5jb250MDI7XG5leHBvcnQgY29uc3QgTXlGaXJzdE1vZHVsZSRjb250MDMgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvTFNHSC9Eb3dubG9hZHMvR2FtZXMtbWFpbi9qYXZhc2NyaXB0c291cmNlL215Zmlyc3Rtb2R1bGUvYWN0aW9ucy9jb250MDNcIikpLmNvbnQwMztcbmV4cG9ydCBjb25zdCBNeUZpcnN0TW9kdWxlJGNvbnQwNCA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL2NvbnQwNFwiKSkuY29udDA0O1xuZXhwb3J0IGNvbnN0IE15Rmlyc3RNb2R1bGUkY29udDA1ID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDA1XCIpKS5jb250MDU7XG5leHBvcnQgY29uc3QgTXlGaXJzdE1vZHVsZSRjb250MDYgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvTFNHSC9Eb3dubG9hZHMvR2FtZXMtbWFpbi9qYXZhc2NyaXB0c291cmNlL215Zmlyc3Rtb2R1bGUvYWN0aW9ucy9jb250MDZcIikpLmNvbnQwNjtcbmV4cG9ydCBjb25zdCBNeUZpcnN0TW9kdWxlJGNvbnQwNyA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy9MU0dIL0Rvd25sb2Fkcy9HYW1lcy1tYWluL2phdmFzY3JpcHRzb3VyY2UvbXlmaXJzdG1vZHVsZS9hY3Rpb25zL2NvbnQwN1wiKSkuY29udDA3O1xuZXhwb3J0IGNvbnN0IE15Rmlyc3RNb2R1bGUkY29udDA4ID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL0xTR0gvRG93bmxvYWRzL0dhbWVzLW1haW4vamF2YXNjcmlwdHNvdXJjZS9teWZpcnN0bW9kdWxlL2FjdGlvbnMvY29udDA4XCIpKS5jb250MDg7XG4iXSwibmFtZXMiOlsiQmlnIiwiVmFsaWRhdGlvbiIsIm1lc3NhZ2UiLCJkb2N1bWVudCIsInF1ZXJ5U2VsZWN0b3IiLCJwMCIsInAxIiwicDIiLCJwMyIsInA0IiwicDUiLCJwNiIsInA3IiwicDgiLCJ0ZXh0Q29udGVudCIsImNvbnQwMCIsIlBsYXllclgiLCJjcmVhdGVFbGVtZW50IiwiUGxheWVyTyIsImNsYXNzTGlzdCIsImNvbnRhaW5zIiwicmVtb3ZlIiwiYWRkIiwiYXBwZW5kQ2hpbGQiLCJpbm5lclRleHQiLCJjb250MDEiLCJjb250MDIiLCJjb250MDMiLCJjb250MDQiLCJjb250MDUiLCJjb250MDYiLCJjb250MDciLCJjb250MDgiLCJNeUZpcnN0TW9kdWxlJGNvbnQwMCIsIk15Rmlyc3RNb2R1bGUkVmFsaWRhdGlvbiIsIk15Rmlyc3RNb2R1bGUkY29udDAxIiwiTXlGaXJzdE1vZHVsZSRjb250MDIiLCJNeUZpcnN0TW9kdWxlJGNvbnQwMyIsIk15Rmlyc3RNb2R1bGUkY29udDA0IiwiTXlGaXJzdE1vZHVsZSRjb250MDUiLCJNeUZpcnN0TW9kdWxlJGNvbnQwNiIsIk15Rmlyc3RNb2R1bGUkY29udDA3IiwiTXlGaXJzdE1vZHVsZSRjb250MDgiXSwic291cmNlUm9vdCI6IiJ9