// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function Validation() {
	// BEGIN USER CODE
	var message = document.querySelector('.mx-name-msg_game')
	var p0 = document.querySelector('.mx-name-id_0')
	var p1 = document.querySelector('.mx-name-id_1')
	var p2 = document.querySelector('.mx-name-id_2')
	var p3 = document.querySelector('.mx-name-id_3')
	var p4 = document.querySelector('.mx-name-id_4')
	var p5 = document.querySelector('.mx-name-id_5')
	var p6 = document.querySelector('.mx-name-id_6')
	var p7 = document.querySelector('.mx-name-id_7')
	var p8 = document.querySelector('.mx-name-id_8')

	if (p0.textContent ==="X" && p1.textContent === "X"  && p2.textContent === "X" ) {
		message.textContent = "PLAYER X WIN!"
	} else if (p3.textContent ==="X" && p4.textContent === "X"  && p5.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p6.textContent ==="X" && p7.textContent === "X"  && p8.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p0.textContent ==="X" && p3.textContent === "X"  && p6.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p1.textContent ==="X" && p4.textContent === "X"  && p7.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p2.textContent ==="X" && p5.textContent === "X"  && p8.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p0.textContent ==="X" && p4.textContent === "X"  && p8.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p2.textContent ==="X" && p4.textContent === "X"  && p6.textContent === "X" ){
		message.textContent = "PLAYER X WIN!"
	} else if (p0.textContent ==="O" && p1.textContent === "O"  && p2.textContent === "O" ) {
		message.textContent = "PLAYER O WIN!"
	} else if (p3.textContent ==="O" && p4.textContent === "O"  && p5.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p6.textContent ==="O" && p7.textContent === "O"  && p8.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p0.textContent ==="O" && p3.textContent === "O"  && p6.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p1.textContent ==="O" && p4.textContent === "O"  && p7.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p2.textContent ==="O" && p5.textContent === "O"  && p8.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p0.textContent ==="O" && p4.textContent === "O"  && p8.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p2.textContent ==="O" && p4.textContent === "O"  && p6.textContent === "O" ){
		message.textContent = "PLAYER O WIN!"
	} else if (p0.textContent != "" && p1.textContent != "" && p2.textContent != "" && p3.textContent != "" 
	&& p4.textContent != "" && p5.textContent != "" && p6.textContent != "" && p7.textContent != "" && p8.textContent != "") {
		message.textContent = ">> TIE <<"
	}
	
	// END USER CODE
}
